//! Philote-Rust: A high-performance library for building MDO analysis servers
//!
//! This library provides a type-safe, async implementation for creating distributed
//! analysis services in Multidisciplinary Design Optimization (MDO) frameworks using
//! gRPC and Protocol Buffers.
//!
//! # Overview
//!
//! Philote enables computational disciplines to be exposed as remote services that can
//! be integrated into MDO frameworks. It supports both explicit and implicit analysis
//! types with automatic gradient computation capabilities.
//!
//! It implements the [Philote-MDO standard](https://github.com/MDO-Standards/Philote-MDO),
//! so disciplines and clients interoperate with the other implementations of the
//! standard, including Philote-Python.
//!
//! # Key features
//!
//! - **Type-safe gRPC communication** using Protocol Buffers
//! - **Async/await support** with the Tokio runtime
//! - **Explicit and implicit disciplines**, with analytic gradients
//! - **Discrete variables** alongside continuous arrays
//! - **Client-resolved shapes** for disciplines sized at runtime
//! - **Chunked streaming** of large arrays
//!
//! # Quick start
//!
//! ## Defining a discipline
//!
//! Metadata lives in a [`VariableRegistry`](registry::VariableRegistry), so an
//! implementation supplies the two accessors — via [`impl_registry!`] — plus the
//! lifecycle hooks it needs.
//!
//! ```rust
//! use async_trait::async_trait;
//! use philote_mdo::{
//!     impl_registry, registry::VariableRegistry,
//!     traits::{Discipline, ExplicitDiscipline},
//!     ArrayMap, Result,
//! };
//! use std::collections::HashMap;
//!
//! #[derive(Default)]
//! struct Doubler {
//!     registry: VariableRegistry,
//! }
//!
//! impl Discipline for Doubler {
//!     impl_registry!(registry);
//!
//!     fn name(&self) -> &str { "Doubler" }
//!
//!     fn setup(&mut self) -> Result<()> {
//!         self.add_input("x", &[3], "m")?;
//!         self.add_output("y", &[3], "m")
//!     }
//! }
//!
//! #[async_trait]
//! impl ExplicitDiscipline for Doubler {
//!     async fn compute(&self, inputs: &ArrayMap) -> Result<ArrayMap> {
//!         let mut outputs = HashMap::new();
//!         outputs.insert("y".to_string(), &inputs["x"] * 2.0);
//!         Ok(outputs)
//!     }
//! }
//! ```
//!
//! ## Connecting with a client
//!
//! ```rust,no_run
//! use philote_mdo::client::ExplicitClient;
//!
//! # async fn example() -> philote_mdo::Result<()> {
//! let mut client = ExplicitClient::connect("http://localhost:50051").await?;
//! let info = client.get_info().await?;
//! println!("Connected to: {} v{}", info.name, info.version);
//!
//! // Required before computing: responses are decoded using the declared shapes.
//! client.setup().await?;
//! client.get_variable_definitions().await?;
//! client.get_partial_definitions().await?;
//! # Ok(())
//! # }
//! ```
//!
//! # Module organization
//!
//! - [`client`] — clients for connecting to Philote servers
//! - [`server`] — servers for hosting disciplines
//! - [`traits`] — discipline trait definitions
//! - [`registry`] — variable, partials, and option metadata storage
//! - [`types`] — data structures and protobuf conversions
//! - [`wire`] — chunk encoding and decoding for variable streams
//! - [`discrete`] — JSON ↔ protobuf `Value` conversions
//! - [`validation`] — input validation helpers
//! - [`error`] — error types
//! - [`utils`] — array helpers
//! - [`examples`] — ready-to-run example disciplines
//!
//! # Type aliases
//!
//! - [`Result<T>`](Result) — standard result type using [`PhiloteError`]
//! - [`ArrayMap`] — map of variable names to N-dimensional arrays
//! - [`PartialMap`] — map of (output, input) pairs to partial derivative arrays
//! - [`DiscreteMap`] — map of variable names to discrete values

#![warn(missing_docs)]

use ndarray::ArrayD;
use std::collections::HashMap;

/// Protocol buffer definitions generated from the Philote MDO specification
#[allow(missing_docs)] // generated by tonic-build; the .proto files are the docs
pub mod philote_info {
    tonic::include_proto!("philote");
}

pub mod client;
pub mod discrete;
pub mod error;
pub mod examples;
pub mod registry;
pub mod server;
pub mod traits;
pub mod types;
pub mod utils;
pub mod validation;
pub mod wire;

pub use error::PhiloteError;
pub use registry::VariableRegistry;
pub use traits::{Discipline, ExplicitDiscipline, ImplicitDiscipline, LinearMode};
pub use types::{ArrayData, VariableData};

/// Standard result type for Philote operations
pub type Result<T> = std::result::Result<T, PhiloteError>;

/// Map of variable names to their N-dimensional array values
pub type ArrayMap = HashMap<String, ArrayD<f64>>;

/// Map of (output variable, input variable) pairs to their partial derivative arrays
pub type PartialMap = HashMap<(String, String), ArrayD<f64>>;

/// Map of discrete variable names to their values
pub type DiscreteMap = HashMap<String, prost_types::Value>;
